ACCDataStore.Web/Areas/SchoolProfile/Controllers/IndexSchoolProfileController.cs
using ACCDataStore.Repository;
using Common.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ACCDataStore.Entity;
using ACCDataStore.Web.Areas.SchoolProfile.ViewModels.EthnicBackground;
using ACCDataStore.Web.Areas.SchoolProfile.ViewModels.IndexSchoolProfile;

namespace ACCDataStore.Web.Areas.SchoolProfile.Controllers
{
    public class IndexSchoolProfileController : BaseSchoolProfileController
    {
        // GET: SchoolProfile/IndexSchoolProfile
        private static ILog log = LogManager.GetLogger(typeof(IndexSchoolProfileController));

        private readonly IGenericRepository rpGeneric;

        public IndexSchoolProfileController(IGenericRepository rpGeneric)
        {
            this.rpGeneric = rpGeneric;
        }

        public ActionResult Index()
        {
            //var vmIndex = new IndexViewModel();
            //var result = this.rpGeneric.FindAll<StudentSIMD>();
            var vmIndexSchoolProfile = new IndexSchoolProfileViewModel();

            var sSchoolName = Request["selectedschoolname"];

            var schoolname = new List<string>();

            var listResult = this.rpGeneric.FindSingleColumnByNativeSQL("SELECT DISTINCTROW Name FROM test_3 group by Name");

            List<string> fooList = listResult.OfType<string>().ToList();

            vmIndexSchoolProfile.ListSchoolNameData = fooList;

            if (sSchoolName == null)
            {
                vmIndexSchoolProfile.selectedschoolname = fooList[0];
                vmIndexSchoolProfile.ListEthnicData = GetEthnicityDatabySchoolname(this.rpGeneric, fooList[0]);
                vmIndexSchoolProfile.ListNationalityData = GetNationalityDatabySchoolname(this.rpGeneric, fooList[0]);
                vmIndexSchoolProfile.ListSIMDData = GetSIMDDatabySchoolname(this.rpGeneric, fooList[0], new List<string>(new string[] { "2012" }));
                vmIndexSchoolProfile.ListStdStageData = GetStudentStageDatabySchoolname(this.rpGeneric, fooList[0]);
            }
            else {
                vmIndexSchoolProfile.selectedschoolname = sSchoolName;
                vmIndexSchoolProfile.ListEthnicData = GetEthnicityDatabySchoolname(this.rpGeneric, sSchoolName);
                vmIndexSchoolProfile.ListNationalityData = GetNationalityDatabySchoolname(this.rpGeneric, sSchoolName);
                vmIndexSchoolProfile.ListSIMDData = GetSIMDDatabySchoolname(this.rpGeneric, sSchoolName, new List<string>(new string[] { "2012" }));
                vmIndexSchoolProfile.ListStdStageData = GetStudentStageDatabySchoolname(this.rpGeneric, sSchoolName);
            
            }



            return View("index", vmIndexSchoolProfile);



        }
        //private Dictionary<string, string> GetDicEhtnicBG()
        //{
        //    var dicNational = new Dictionary<string, string>();
        //    dicNational.Add("01", "White – Scottish");
        //    dicNational.Add("02", "African – African / Scottish / British");
        //    dicNational.Add("03", "Caribbean or Black – Caribbean / British / Scottish");
        //    dicNational.Add("05", "Asian – Indian/British/Scottish");
        //    dicNational.Add("06", "Asian – Pakistani / British / Scottish");
        //    dicNational.Add("07", "Asian –Bangladeshi / British / Scottish");
        //    dicNational.Add("08", "Asian – Chinese / British / Scottish");
        //    dicNational.Add("09", "White – Other");
        //    dicNational.Add("10", "Not Disclosed");
        //    dicNational.Add("12", "Mixed or multiple ethnic groups");
        //    dicNational.Add("17", "Asian – Other");
        //    dicNational.Add("19", "White – Gypsy/Traveller");
        //    dicNational.Add("21", "White – Other British");
        //    dicNational.Add("22", "White – Irish");
        //    dicNational.Add("23", "White – Polish");
        //    dicNational.Add("24", "Caribbean or Black – Other");
        //    dicNational.Add("25", "African – Other");
        //    dicNational.Add("27", "Other – Arab");
        //    dicNational.Add("98", "Not Known");
        //    dicNational.Add("99", "Other – Other");
        //    return dicNational;
        //}

            

    }
}

ACCDataStore.Web/Areas/SchoolProfile/Controllers/NationalityController.cs
using ACCDataStore.Entity;
using ACCDataStore.Repository;
using ACCDataStore.Web.Areas.SchoolProfile.ViewModels.Nationality;
using ClosedXML.Excel;
using Common.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ACCDataStore.Web.Areas.SchoolProfile.Controllers
{
    public class NationalityController : BaseSchoolProfileController
    {
        private static ILog log = LogManager.GetLogger(typeof(NationalityController));

        private readonly IGenericRepository rpGeneric;

        public NationalityController(IGenericRepository rpGeneric)
        {
            this.rpGeneric = rpGeneric;
        }
        // GET: SchoolProfile/Nationality
        public ActionResult Index(string sSchoolName)
        {
            var vmNationality = new NationalityViewModel();

            var schoolname = new List<string>();
            var sNationalCriteria = new List<string>();
            var setGenderCriteria = new List<string>();

            List<NationalityObj> ListNationalData = new List<NationalityObj>();
            List<NationalityObj> temp = new List<NationalityObj>();


            var listResult = this.rpGeneric.FindSingleColumnByNativeSQL("SELECT DISTINCTROW Name FROM test_3 group by Name");

            List<string> fooList = listResult.OfType<string>().ToList();

            vmNationality.ListSchoolNameData = fooList;


            listResult = this.rpGeneric.FindSingleColumnByNativeSQL("SELECT DISTINCTROW NationalIdentity FROM test_3 group by NationalIdentity");

            fooList = listResult.OfType<string>().ToList();
            vmNationality.ListNationalCode = fooList;
            vmNationality.DicNational = GetDicNational();

            listResult = this.rpGeneric.FindSingleColumnByNativeSQL("SELECT DISTINCTROW Gender FROM test_3 group by Gender");

            fooList = listResult.OfType<string>().ToList();

            vmNationality.ListGenderCode = fooList;
            vmNationality.DicGender = GetDicGender();


            if (Request.HttpMethod == "GET") // get method
            {
                if (sSchoolName == null) // case of index page, show criteria
                {
                    vmNationality.IsShowCriteria = true;
                }
                else // case of detail page, by pass criteria
                {
                    vmNationality.IsShowCriteria = false;
                    vmNationality.ListSelectedGender = new List<string>(new string[] { "Total" });
                    Session["ListSelectedGender"] = vmNationality.ListSelectedGender;
                    Session["sSchoolName"] = sSchoolName;
                }

            }
            else // post method
            {
                vmNationality.IsShowCriteria = true;
                sSchoolName = Request["selectSchoolname"];
                Session["sSchoolName"] = sSchoolName;

                if (Request["nationality"] != null)
                {
                    sNationalCriteria = Request["nationality"].Split(',').ToList();
                }
                else
                {
                    sNationalCriteria = null;
                }
                if (Request["gender"] != null)
                {
                    vmNationality.ListSelectedGender = Request["gender"].Split(',').ToList();
                }
                else
                {
                    vmNationality.ListSelectedGender = new List<string>(new string[] { "Total" });
                }               
                
                Session["ListSelectedGender"] = vmNationality.ListSelectedGender;
                // get parameter from Request object
            }

            vmNationality.DicGenderWithSelected = GetDicGenderWithSelected(vmNationality.ListSelectedGender);

            // process data
            if (sSchoolName != null)
            {
                vmNationality.selectedschoolname = sSchoolName;
                ListNationalData = GetNationalityDatabySchoolname(rpGeneric,sSchoolName);

                if (sNationalCriteria == null)
                {
                    vmNationality.ListNationalityData = null;
                }
                else if (sNationalCriteria.Count != 0 && sNationalCriteria != null)
                {
                    vmNationality.ListNationalityData = ListNationalData.Where(x => sNationalCriteria.Contains(x.IdentityCode)).ToList();
                }
                else
                {
                    vmNationality.ListNationalityData = ListNationalData;
                }                
                Session["SessionListNationalityData"] = vmNationality.ListNationalityData;
            }
            return View("Index", vmNationality);
        }

        //public List<NationalityObj> GetNationalityDatabySchoolname(string mSchoolname)
        //{
        //    Console.Write("GetNationalityData ==> ");

        //    var singlelistChartData = new List<ChartData>();
        //    List<NationalityObj> listDataseries = new List<NationalityObj>();
        //    List<NationalityObj> listtemp = new List<NationalityObj>();
        //    NationalityObj tempNationalObj = new NationalityObj();
            

        //    //% for All school
        //    var listResult = this.rpGeneric.FindByNativeSQL("Select NationalIdentity, (Count(NationalIdentity)* 100 / (Select Count(*) From test_3))  From test_3  Group By NationalIdentity ");
        //    if (listResult != null)
        //    {
        //        foreach (var itemRow in listResult)
        //        {
        //            tempNationalObj = new NationalityObj();
        //            tempNationalObj.IdentityCode = Convert.ToString(itemRow[0]);
        //            tempNationalObj.IdentityName = GetDicNational().ContainsKey(tempNationalObj.IdentityCode) ? GetDicNational()[tempNationalObj.IdentityCode] : "NO NAME";
        //            tempNationalObj.PercentageAllSchool = Convert.ToDouble(itemRow[1]);
        //            listtemp.Add(tempNationalObj);

        //            //tempNationalObj = listtemp.Find(x => x.IdentityCode.Equals(Convert.ToString(itemRow[0])));
        //            //tempNationalObj.PercentageAllSchool = Convert.ToDouble(itemRow[1]);

        //            //listDataseries.Add(tempNationalObj);
        //        }
        //    }


        //    //% for specific schoolname
        //    string query = " Select NationalIdentity, (Count(NationalIdentity)* 100 /";
        //    query += " (Select Count(*) From test_3 where Name in ('" + mSchoolname + " ')))";
        //    query += " From test_3 where Name in ('" + mSchoolname + " ') Group By NationalIdentity ";

        //    listResult = this.rpGeneric.FindByNativeSQL(query);

        //    if (listResult != null)
        //    {
        //        foreach (var itemRow in listResult)
        //        {
        //            //tempNationalObj = new NationalityObj();
        //            //tempNationalObj.IdentityCode = Convert.ToString(itemRow[0]);
        //            //tempNationalObj.IdentityName = GetDicNational().ContainsKey(tempNationalObj.IdentityCode) ? GetDicNational()[tempNationalObj.IdentityCode] : "NO NAME";
        //            //tempNationalObj.PercentageInSchool = Convert.ToDouble(itemRow[1]);
        //            //listtemp.Add(tempNationalObj);
        //            tempNationalObj = listtemp.Find(x => x.IdentityCode.Equals(Convert.ToString(itemRow[0])));
        //            tempNationalObj.PercentageInSchool = Convert.ToDouble(itemRow[1]);

        //            listDataseries.Add(tempNationalObj);
 
        //        }
        //    }


        //    return listDataseries;
        //}

        //private Dictionary<string, string> GetDicNational()
        //{
        //    var dicNational = new Dictionary<string, string>();
        //    dicNational.Add("01", "Scottish");
        //    dicNational.Add("02", "English");
        //    dicNational.Add("03", "Northern Irish");
        //    dicNational.Add("04", "Welsh");
        //    dicNational.Add("05", "British");
        //    dicNational.Add("99", "Other");
        //    dicNational.Add("10", "Not Disclosed");
        //    dicNational.Add("98", "Not Known");
        //    return dicNational;
        //}

        [HttpPost]
        public JsonResult GetChartDataNationality(string[] arrParameterFilter)
        {
            try
            {
                object oChartData = new object();
                string[] Categories = new string[arrParameterFilter.Length];

                var listNationalData = Session["SessionListNationalityData"] as List<NationalityObj>;
                if (listNationalData != null)
                {
                    var listNationalFilter = listNationalData.Where(x => arrParameterFilter.Contains(x.IdentityCode)).ToList();


                    // process chart data
                    oChartData = new
                    {
                        ChartTitle = "test",
                        ChartCategories = listNationalFilter.Select(x => x.IdentityName).ToArray(),
                        ChartSeries = ProcessChartDataEthnic(listNationalFilter)
                    };
                }


                return Json(oChartData, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                log.Error(ex.Message, ex);
                throw ex;
            }
        }

        private List<object> ProcessChartDataEthnic(List<NationalityObj> listNationalFilter)
        {
            var listChartData = new List<object>();
            var ListSelectedGender = Session["ListSelectedGender"] as List<string>;
            var schoolname = Session["sSchoolName"];

            foreach (var itemGender in ListSelectedGender)
            {
                if (itemGender.Equals("F"))
                {

ACCDataStore.Web/Controllers/IndexController.cs
using Common.Logging;
using System;
using System.Web;
using System.Web.Mvc;
using ACCDataStore.Repository;
using ACCDataStore.Entity;
using ACCDataStore.Web.ViewModels;

namespace ACCDataStore.Web.Controllers
{
    public class IndexController : BaseController
    {
        private static ILog log = LogManager.GetLogger(typeof(IndexController));

        private readonly IGenericRepository rpGeneric;
        public IndexController(IGenericRepository rpGeneric)
        {
            this.rpGeneric = rpGeneric;
        }

        public ActionResult Index(string id)
        {
            // just git test
            if (id == null)
            {
                var vmIndex = new IndexViewModel();
                vmIndex.ApplicationName = HttpContext.Application["APP_NAME"] as string;
                vmIndex.ApplicationVersion = HttpContext.Application["APP_VERSION"] as string;
                return View("index", vmIndex);
               
            }
            else
            {
                return View("theTeam");
            }
            
        }
    }
}

ACCDataStore.Web/Areas/SchoolProfile/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@HttpContext.Current.Application["APP_NAME"]</title>
    <link rel="stylesheet" href="~/Content/accdatastore/views/global.css" type="text/css" />
    <script src="~/Scripts/accdatastore/views/global.js"></script>
    <script src="~/Scripts/jquery-2.1.1.min.js"></script>
    <script src="~/Scripts/highcharts.js"></script>
    <script>
        var sContextPath = '@Url.Content("~")';
    </script>
    @RenderSection("Header")
</head>
@*<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>*@

<body>
    <div id="divBody">
        <div id="container">
            <div id="header">
                <h1> Aberdeen City Council Digital Data Observatory Project</h1>
            </div>
            <div id="content">
                <div id="nav">
                    <h3>Navigation</h3>
                    <ul>
                        <li>@Html.ActionLink("Home", "Index", "Index", new { Area = "" }, null)</li>  
                        <li>@Html.ActionLink("School Profile", "Index", "IndexSchoolProfile", new { Area = "SchoolProfile" }, null)</li>  
                        @*<li>@Html.ActionLink("School Roll", "Index", "Nationality", new { Area = "SchoolProfile" }, null)</li>
                        <li>@Html.ActionLink("PIPS", "Index", "Nationality", new { Area = "SchoolProfile" }, null)</li>
                        <li>@Html.ActionLink("Attendance", "Index", "SchoolProfile", new { Area = "SchoolProfile" }, null)</li>
                        <li>@Html.ActionLink("Exclusion Annual", "Index", "SchoolProfile", new { Area = "SchoolProfile" }, null)</li>
                        <li>@Html.ActionLink("Violent Incidents Annual", "Index", "SchoolProfile", new { Area = "SchoolProfile" }, null)</li>
                        <li>@Html.ActionLink("Scottish Index of Multiple Deprivation", "Index", "SchoolProfile", new { Area = "SchoolProfile" }, null)</li>*@
                        <li>@Html.ActionLink("EthnicBackground", "Index", "EthnicBackground", new { Area = "SchoolProfile", sSchoolName = "" }, null)</li>
                        <li>@Html.ActionLink("Nationality", "Index", "Nationality", new { Area = "SchoolProfile", sSchoolName = "" }, null)</li>
                        <li>@Html.ActionLink("SIMD", "Index", "SIMD", new { Area = "SchoolProfile", sSchoolName = "" }, null)</li>
                        <li>@Html.ActionLink("Stage", "Index", "StudentStage", new { Area = "SchoolProfile", sSchoolName = "" }, null)</li>
                        @*<li>@Html.ActionLink("Occupancy", "Index", "SchoolProfile", new { Area = "SchoolProfile" }, null)</li>*@
                    </ul>
                </div>
                <div id="main">
                    @RenderBody()
                </div>
            </div>
            <div id="footer">
                Aberdeen City Council
            </div>
        </div>
    </div>
</body>
</html>