ACCDataStore.Web/Areas/Nationality/Controllers/IndexNationalityController.cs
using ACCDataStore.Entity;
using ACCDataStore.Repository;
using ACCDataStore.Web.Areas.Nationality.ViewModels.IndexNationality;
using Common.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ACCDataStore.Web.Areas.Nationality.Controllers
{
    public class IndexNationalityController : Controller
    {
        private static ILog log = LogManager.GetLogger(typeof(IndexNationalityController));

        private readonly IGenericRepository rpGeneric;
        public IndexNationalityController(IGenericRepository rpGeneric)
        {
            this.rpGeneric = rpGeneric;
        }

        public ActionResult Index()
        {
            var vmIndex = new IndexViewModel();
            vmIndex.ListNationality2012 = this.rpGeneric.Find<Nationality2012>(" from Nationality2012 where Gender = :Gender ", new string[] { "Gender" }, new object[] { "M" });

            return View(vmIndex);
        }
    }
}

ACCDataStore.Web/Controllers/IndexController.cs
using Common.Logging;
using System;
using System.Web;
using System.Web.Mvc;
using ACCDataStore.Repository;
using ACCDataStore.Entity;
using ACCDataStore.Web.ViewModels;

namespace ACCDataStore.Web.Controllers
{
    public class IndexController : BaseController
    {
        private static ILog log = LogManager.GetLogger(typeof(IndexController));

        private readonly IGenericRepository rpGeneric;
        public IndexController(IGenericRepository rpGeneric)
        {
            this.rpGeneric = rpGeneric;
        }

        public ActionResult Index(string id)
        {
            // just git test
            if (id == null)
            {
                var vmIndex = new IndexViewModel();
                vmIndex.ApplicationName = HttpContext.Application["APP_NAME"] as string;
                vmIndex.ApplicationVersion = HttpContext.Application["APP_VERSION"] as string;
                return View("index", vmIndex);
               
            }
            else
            {
                return View("theTeam");
            }
            
        }
    }
}

ACCDataStore.Web/Views/Index/Index.cshtml
@section Header {
    <link rel="stylesheet" href="~/Content/accdatastore/views/index/index.css" type="text/css" />
    <script src="~/Scripts/accdatastore/views/index/index.js"></script>
}
@*@HttpContext.Current.Application["APP_NAME"] @HttpContext.Current.Application["APP_VERSION"]
    <br />
    @Html.ActionLink("Nationality Test", "Index", "IndexNationality", new { Area = "Nationality" }, null)
    @Html.ActionLink("Nationality", "Index", "Nationality", new { Area = "Nationality" }, null)*@

<div>
    <h2> Home</h2>
    <p>Welcome to Aberdeen data Observatory Project. This website pull all project data together providing an up-to-data information on Digital Data Observatory Project for Aberdeen City Council. The aim of this project is to provide an easy access to a wide rang of information collected from local data source and can be analysed and enhanced decision making based on a robust evidence based for decision makers.</p>
</div>

ACCDataStore.Web/Views/Index/theTeam.cshtml
@section Header {
    <link rel="stylesheet" href="~/Content/accdatastore/views/index/index.css" type="text/css" />
    <script src="~/Scripts/accdatastore/views/index/index.js"></script>
}
@*@HttpContext.Current.Application["APP_NAME"] @HttpContext.Current.Application["APP_VERSION"]
    <br />
    @Html.ActionLink("Nationality Test", "Index", "IndexNationality", new { Area = "Nationality" }, null)
    @Html.ActionLink("Nationality", "Index", "Nationality", new { Area = "Nationality" }, null)*@

<div>
    <h2> The Team</h2>
    <h2>Lead Academic/Researcher</h2>
    <h3>Professor Do Coyle</h3>
    <img src="@Url.Content("~/Images/Do_Coyle.jpg")" alt="Do_Coyle" />
    <h4>Do Coyle’s work focuses on technology-enhanced learning especially in developing end-user tools for enhancing performance and practice (e.g. interactive video networked spaces linking classrooms, universities and workplaces in schools, vet practices and community organisations). Specialist in multi-disciplinary higher education and adult visual learning; blending workplace and academic learning; current and recent cross-disciplinary funding from AHRC Connected Communities, European initiatives, Esmee Fairbairn and Scottish Government. Products of research range from interactive digital tools for practitioner analysis of own work practices and co-creation of practice-based data bases with participants to enhance professional practice to on-line interactive needs analysis tools for professional training. Former co-director of University of Nottingham’s multimillion HEFCE funded Visual Learning Lab, Do currently supervises 6 PhD students and two European doctorates.</h4>
    <br>
    <h2>Company Supervisor</h2>
    <h3>Kevin Stelfox</h3>    
    <img src="@Url.Content("~/Images/Kevin.jpeg")" alt="Kevin" />
    <h4>25 year career in local government research, performance and policy across Social Work and Education Services, Hon Research fellow at Aberdeen University and 15 years experience of managing teams and line management of staff.</h4>
    <br>
    <h2>Company Supervisor</h2>
    <h3>Pamela Bain</h3>
    <img src="@Url.Content("~/Images/Pamela_Bain.jpeg")" alt="Pamela" />
    <h4>Pamela’s role is Research and New Projects Development Officer for Education and Children’s Directorate. This role provides professional advice, support and effective management of the Directorate’s research functions. She is responsible for the development of the Education and Children’s Directorate research and evaluation programmes. Pamela has presented research papers at National level at the Scottish Government Learning Festival and Glasgow University Scottish Education Research Association annual conference. Pamela has over twenty five years of management and supervisory experience within various local authority departments. Her previous role was that of Service Improvement Manager within the council’s neighbourhood services, south area.</h4>
    <br>
    <h2>Facilitator</h2>
    <h3>Sarah Gear</h3>
    <img src="@Url.Content("~/Content/Images/Jan2.png")" alt="Sarah" />
    <h4>24 year career in local government performance management and quality assurance, external consultancy, coaching and mentoring, resource management, NLP training and matrix management of teams.</h4>
    <br>
    <h2>Knowledge Base Supervisor</h2>
    <h3>Dr Ian Heywood</h3>
    <img src="@Url.Content("~/Images/Ian_Heywood.jpg")" alt="Ian" />
    <h4>Dr Ian Heywood teaches Business Strategy, Leadership and Enterprise and has research interested in digital technology and it role in decision-making. Prior to joining the University he was Director of the Ideas Academy Ltd and Director of Growing Business and Skills with Scottish Enterprise Grampian. In both these rolls Dr Heywood was directly involved in using public data to support policymaking.  Dr Heywood also has a PhD in Geography specialising in Geographic Information Systems.</h4>
    <br>
    <h2>Knowledge Base Supervisor</h2>
    <h3>Dr Bruce Scharlau</h3>
    <img src="@Url.Content("~/Images/bruce_scharlau.jpg")" alt="Bruce" />
    <h4>Teaches advanced web application development for the last eleven years and provided conference talks on using agile development. As director of the Aberdeen Software Factory for the last two years has helped numerous small firms develop bespoke software with the help of students. Also trained facilitator in Strategic Play® Lego Serious Play process for co-creative development and strategic approaches to find creative solutions to difficult problems. </h4>
    <br>
    <h2>KTP Associate</h2>
    <h3>Dr Hataichanok Saevanee</h3>
    <img src="@Url.Content("~/Images/Jan2.png")" alt="Jan" />
    <h4>Jan has a strong background in computer science area covering material such as mathematics for computing, software development, database, project management, data structures and algorithms. She had experience working as a software engineering developing web application for student registration services. Prior to join the project, she was a lecturer and demonstrator for several computer programming languages at Ubonratchathani University and Plymouth University.</h4>

    
</div>