ACCDataStore.Web/Areas/SchoolProfile/ViewModels/StudentStage/StudentStageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ACCDataStore.Web.Areas.SchoolProfile.ViewModels.StudentStage
{
    public class StudentStageViewModel : SchoolProfileViewModel
    {
        // public List<SIMDObj> ListSIMDdata { get; set; }
        public List<string> ListStage { get; set; }
        public bool IsShowCriteria { get; set; }
    }
}

ACCDataStore.Web/Areas/SchoolProfile/Controllers/StudentStageController.cs
using ACCDataStore.Entity.SchoolProfile;
using ACCDataStore.Repository;
using ACCDataStore.Web.Areas.SchoolProfile.ViewModels.StudentStage;
using ClosedXML.Excel;
using Common.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ACCDataStore.Web.Areas.SchoolProfile.Controllers
{
    public class StudentStageController : BaseSchoolProfileController
    {
        private static ILog log = LogManager.GetLogger(typeof(NationalityController));

        private readonly IGenericRepository rpGeneric;

        public StudentStageController(IGenericRepository rpGeneric)
        {
            this.rpGeneric = rpGeneric;
        }
        // GET: SchoolProfile/StudentStage
        public ActionResult Index(string sSchoolName)
        {
            var vmStudentStage = new StudentStageViewModel();

            var schoolname = new List<string>();
            var sStageCriteria = new List<string>();
            var setGenderCriteria = new List<string>();

            List<StdStageObj> ListStdStageData = new List<StdStageObj>();
            List<StdStageObj> temp = new List<StdStageObj>();


            var listResult = this.rpGeneric.FindSingleColumnByNativeSQL("SELECT DISTINCTROW Name FROM test_3 group by Name");

            List<string> fooList = listResult.OfType<string>().ToList();

            vmStudentStage.ListSchoolNameData = fooList;


            listResult = this.rpGeneric.FindSingleColumnByNativeSQL("SELECT DISTINCTROW StudentStage FROM test_3 group by StudentStage");

            fooList = listResult.OfType<string>().ToList();
            vmStudentStage.ListStage = fooList;


            listResult = this.rpGeneric.FindSingleColumnByNativeSQL("SELECT DISTINCTROW Gender FROM test_3 group by Gender");

            fooList = listResult.OfType<string>().ToList();

            vmStudentStage.ListGenderCode = fooList;
            vmStudentStage.DicGender = GetDicGender();


            if (Request.HttpMethod == "GET") // get method
            {
                if (sSchoolName == null) // case of index page, show criteria
                {
                    vmStudentStage.IsShowCriteria = true;
                }
                else // case of detail page, by pass criteria
                {
                    vmStudentStage.IsShowCriteria = false;
                    vmStudentStage.ListSelectedGender = new List<string>(new string[] { "Total" });
                    Session["ListSelectedGender"] = vmStudentStage.ListSelectedGender;
                    Session["sSchoolName"] = sSchoolName;
                }

            }
            else // post method
            {
                vmStudentStage.IsShowCriteria = true;
                sSchoolName = Request["selectSchoolname"];
                Session["sSchoolName"] = sSchoolName;

                if (Request["stages"] != null)
                {
                    sStageCriteria = Request["stages"].Split(',').ToList();
                }
                else
                {
                    sStageCriteria = null;
                }
                if (Request["gender"] != null)
                {
                    vmStudentStage.ListSelectedGender = Request["gender"].Split(',').ToList();
                }
                else
                {
                    vmStudentStage.ListSelectedGender = new List<string>(new string[] { "Total" });
                }

                Session["ListSelectedGender"] = vmStudentStage.ListSelectedGender;
                // get parameter from Request object
            }

            vmStudentStage.DicGenderWithSelected = GetDicGenderWithSelected(vmStudentStage.ListSelectedGender);

            // process data
            if (sSchoolName != null)
            {
                vmStudentStage.selectedschoolname = sSchoolName;
                ListStdStageData = GetStudentStageDatabySchoolname(rpGeneric, sSchoolName);

                if (sStageCriteria == null)
                {
                    vmStudentStage.ListStdStageData = null;
                }
                else if (sStageCriteria.Count != 0 && sStageCriteria != null)
                {
                    vmStudentStage.ListStdStageData = ListStdStageData.Where(x => sStageCriteria.Contains(x.StageCode)).ToList();
                }
                else
                {
                    vmStudentStage.ListStdStageData = ListStdStageData;
                }
                Session["SessionListStudentStageData"] = vmStudentStage.ListStdStageData;
            }
            return View("Index", vmStudentStage);
        }

        [HttpPost]
        public JsonResult GetChartDataStudentStage(string[] arrParameterFilter)
        {
            try
            {
                object oChartData = new object();
                string[] Categories = new string[arrParameterFilter.Length];

                var listStdStageData = Session["SessionListStudentStageData"] as List<StdStageObj>;
                if (listStdStageData != null)
                {
                    var listStdStageFilter = listStdStageData.Where(x => arrParameterFilter.Contains(x.StageCode)).ToList();


                    // process chart data
                    oChartData = new
                    {
                        ChartTitle = "Stage",
                        ChartCategories = listStdStageFilter.Select(x => x.StageCode).ToArray(),
                        ChartSeries = ProcessChartDataStdStage(listStdStageFilter)
                    };
                }


                return Json(oChartData, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                log.Error(ex.Message, ex);
                throw ex;
            }
        }

        private List<object> ProcessChartDataStdStage(List<StdStageObj> listStdStageFilter)
        {
            var listChartData = new List<object>();
            var ListSelectedGender = Session["ListSelectedGender"] as List<string>;
            var schoolname = Session["sSchoolName"];

            foreach (var itemGender in ListSelectedGender)
            {
                if (itemGender.Equals("F"))
                {
                    listChartData.Add(new { name = "FemaleAllSchool", data = listStdStageFilter.Select(x => x.PercentageFemaleAllSchool).ToArray() });
                    listChartData.Add(new { name = schoolname + " Female", data = listStdStageFilter.Select(x => x.PercentageFemaleInSchool).ToArray() });
                }

                if (itemGender.Equals("M"))
                {
                    listChartData.Add(new { name = "MaleAllSchool", data = listStdStageFilter.Select(x => x.PercentageMaleAllSchool).ToArray() });
                    listChartData.Add(new { name = schoolname + " Male", data = listStdStageFilter.Select(x => x.PercentageMaleInSchool).ToArray() });
                }
                if (itemGender.Equals("Total"))
                {
                    listChartData.Add(new { name = "TotalAllSchool", data = listStdStageFilter.Select(x => x.PercentageAllSchool).ToArray() });
                    listChartData.Add(new { name = schoolname + " Total", data = listStdStageFilter.Select(x => x.PercentageInSchool).ToArray() });
                }

            }
            return listChartData;
        }

        public ActionResult ExportExcel()
        {
            var listStdStageData = Session["SessionListStudentStageData"] as List<StdStageObj>;
            string schoolname = Session["sSchoolName"].ToString();

            var dataStream = GetWorkbookDataStream(listStdStageData, schoolname);
            return File(dataStream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "export.xlsx");
        }

        private MemoryStream GetWorkbookDataStream(List<StdStageObj> dtResult, string schoolname)
        {
            var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add("Sheet 1");
            worksheet.Cell("A1").Value = schoolname; // use cell address in range
            worksheet.Cell("A2").Value = "Student Stages"; // use cell address in range
            worksheet.Cell(3, 1).InsertTable(dtResult); // use row & column index
            worksheet.Rows().AdjustToContents();
            worksheet.Columns().AdjustToContents();

            var memoryStream = new MemoryStream();
            workbook.SaveAs(memoryStream);
            memoryStream.Seek(0, SeekOrigin.Begin);
            return memoryStream;
        }
    }
}

ACCDataStore.Web/Areas/SchoolProfile/Views/StudentStage/Index.cshtml
@model ACCDataStore.Web.Areas.SchoolProfile.ViewModels.StudentStage.StudentStageViewModel
@section Header {
    <link rel="stylesheet" href="~/Content/accdatastore/areas/nationality/views/nationality/nationality.css" type="text/css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.css" type="text/css" />
    <script src="~/Scripts/accdatastore/areas/schoolprofile/views/StudentStage/StudentStage.js"></script>
    <script type="text/javascript" src="http://code.highcharts.com/modules/exporting.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
}
@{
    ViewBag.Title = "Index";
}

<h2>@Model.selectedschoolname</h2>

<h2>Stage - Primary School (%pupils)</h2>
@if (Model.IsShowCriteria)
{
    using (Html.BeginForm("Index", "StudentStage", new { area = "SchoolProfile" }))
    {
        <table>
            <tr>
                <th colspan="2">Please select Criteria</th>
            </tr>
            <tr>
                <td colspan="2">Select school name </td>
            </tr>
            <tr>
                <td></td>
                <td>@Html.DropDownList("selectSchoolname", new SelectList(Model.ListSchoolNameData, "----Select------"))</td>
            </tr>
            <tr>
                <td colspan="2">Select Gender </td>
            </tr>

            @*@foreach (var itemGender in Model.ListGenderCode)
                {
                    if (Model.DicGender.ContainsKey(itemGender))
                    {
                        <tr>
                            <td></td>
                            <td>
                                <input type="checkbox" name="gender" value="@itemGender"
                                       checked="checked" /> @Model.DicGender[itemGender]
                                </td>
                            </tr>
                    }
                }*@
            @foreach (var itemGender in Model.ListGenderCode)
            {
                if (Model.DicGenderWithSelected.ContainsKey(itemGender))
                {
                    <tr>
                        <td></td>
                        <td>
                            <input type="checkbox" name="gender" value="@itemGender"
                                   @Model.DicGenderWithSelected[itemGender][1] /> @Model.DicGenderWithSelected[itemGender][0]
                            </td>
                        </tr>
                }
            }
            <tr>
                <td></td>
                <td>
                    <input type="checkbox" name="gender" value="Total"
                           checked="checked" />Total
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="checkbox" name="CheckGenderAll"
                           value="ALL" id="CheckGenderAll" checked="checked" />CheckALL
                </td>

            </tr>
            <tr>
                <td colspan="2">Select Stage </td>
            </tr>
            @foreach (var itemStage in Model.ListStage)
            {
                <tr>
                    <td></td>
                    <td>
                        <input type="checkbox" name="stages" value="@itemStage"
                               checked="checked" /> @itemStage
                        </td>
                    </tr>
            }
           <tr>
                <td></td>
                <td>
                    <input type="checkbox" name="CheckStageAll"
                           value="ALL" id="CheckStageAll" checked="checked" />CheckALL
                </td>

            </tr>
            <tr>
                <td>
                    <button id="buttonGetData" type="submit">
                        Get Data
                    </button>
                </td>
            </tr>


        </table>
    }
}
@if (Model.ListStdStageData != null)
{
    <br />
    <form id="StdStageData">
        <table id="datatable" class="display">
            <thead>
                <tr>
                    <th rowspan="2">Stage</th>
                    @if (Model.ListSelectedGender != null && Model.ListSelectedGender.Count != 0)
                    {
                        foreach (var selection in Model.ListSelectedGender)
                        {
                            if (selection.Equals("F"))
                            {
                                <th colspan="2">Female</th>
                            }
                            if (selection.Equals("M"))
                            {
                                <th colspan="2">Male</th>
                            }
                            if (selection.Equals("Total"))
                            {
                                <th colspan="2">Total</th>
                            }
                        }
                    }
                    <th rowspan="2">Select data </th>
                </tr>
                <tr>

                    @if (Model.ListSelectedGender != null && Model.ListSelectedGender.Count != 0)
                    {
                        foreach (var selection in Model.ListSelectedGender)
                        {
                            if (selection.Equals("F"))
                            {
                                <th>@Model.selectedschoolname</th>
                                <th>All Primary Schools</th>
                            }
                            if (selection.Equals("M"))
                            {
                                <th>@Model.selectedschoolname</th>
                                <th>All Primary Schools</th>
                            }
                            if (selection.Equals("Total"))
                            {
                                <th>@Model.selectedschoolname</th>
                                <th>All Primary Schools</th>
                            }
                        }
                    }

                </tr>
            </thead>
            <tbody>
                @foreach (var itemStdStage in Model.ListStdStageData)
                {

                    <tr>
                        <td>@itemStdStage.StageCode</td>

                        @if (Model.ListSelectedGender != null && Model.ListSelectedGender.Count != 0)
                        {
                            foreach (var selection in Model.ListSelectedGender)
                            {
                                if (selection.Equals("F"))
                                {
                                    <td align="center">@String.Format("{0:#,0.00}", @itemStdStage.PercentageFemaleInSchool)</td>
                                    <td align="center">@String.Format("{0:#,0.00}", @itemStdStage.PercentageFemaleAllSchool)</td>
                                }
                                if (selection.Equals("M"))
                                {
                                    <td align="center">@String.Format("{0:#,0.00}", @itemStdStage.PercentageMaleInSchool)</td>
                                    <td align="center">@String.Format("{0:#,0.00}", @itemStdStage.PercentageMaleAllSchool)</td>
                                }
                                if (selection.Equals("Total"))
                                {
                                    <td align="center">@String.Format("{0:#,0.00}", @itemStdStage.PercentageInSchool)</td>
                                    <td align="center">@String.Format("{0:#,0.00}", @itemStdStage.PercentageAllSchool)</td>
                                }
                            }
                        }

                        <td align="center"><input type='checkbox' name='CheckDataitem' value="@itemStdStage.StageCode" checked="checked" /></td>
                    </tr>
                }
            </tbody>
            <tr>
                @{var colspan = (@Model.ListSelectedGender.Count * 2) + 1;}
                <td colspan=@colspan></td>
                <td align="center"><input type='checkbox' name='CheckDataitemAll' id='CheckDataitemAll' value="ALL" checked="checked" />CheckALL</td>
            </tr>
            <tr><td><button onclick='myFunctionBar()'><label>Bar Chart</label></button></td></tr>
            <tr><td><button onclick='myFunctionColumn()'><label>Column Chart</label></button></td></tr>
            <tr><td>@Html.ActionLink("Export Excel", "ExportExcel", "StudentStage", new { Area = "SchoolProfile", sSchoolName = "" }, null)</td></tr>
        </table>
        <script type="text/javascript">
            // Put your javascript code here
            $('#datatable').DataTable({
                paging: false
            });
        </script>

        <div id="divChartContainer"></div>

        <br>
    </form>
}